#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias phone="adb connect 192.168.2.34 && scrcpy"

# Maintenance Aliases
alias maintain="yay -Syu && yay -Scc"
alias update="yay -Syu"
alias cache="yay -Scc"
alias orphans="yay -Qttdq | yay -Rns -"
alias packages="yay -Qq"

# Operation Aliases
alias clear="clear && neofetch"
alias install="yay -S"
alias remove="yay -Rns"
alias force-remove="yay -Rdd"
alias edit="sudo nano"
alias delete="sudo rm -rf"

#Prompt
PS1='\W > '

neofetch

# ORIGINAL
#
# ~/.bashrc
#

# If not running interactively, don't do anything
#[[ $- != *i* ]] && return

#alias ls='ls --color=auto'
#PS1='[\u@\h \W]\$ '
